//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService_App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BroomService_App.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us .
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex. doorman/elock/keybox/key/other.
        /// </summary>
        internal static string AccessProperty {
            get {
                return ResourceManager.GetString("AccessProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access To Property (With Details).
        /// </summary>
        internal static string AccessPropertyTitle {
            get {
                return ResourceManager.GetString("AccessPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access To Property (With Details).
        /// </summary>
        internal static string AccessPropertyWithDetails {
            get {
                return ResourceManager.GetString("AccessPropertyWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job Request.
        /// </summary>
        internal static string AddJobRequestBtn {
            get {
                return ResourceManager.GetString("AddJobRequestBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Property.
        /// </summary>
        internal static string AddProperty {
            get {
                return ResourceManager.GetString("AddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can list as many properties you want for each kind..
        /// </summary>
        internal static string AddPropertyHeaderMsg {
            get {
                return ResourceManager.GetString("AddPropertyHeaderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4200 Green Gate Lane.
        /// </summary>
        internal static string AddressValue {
            get {
                return ResourceManager.GetString("AddressValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string ago {
            get {
                return ResourceManager.GetString("ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string AlreadyAccountMsg {
            get {
                return ResourceManager.GetString("AlreadyAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC Apartment.
        /// </summary>
        internal static string ApartmentName {
            get {
                return ResourceManager.GetString("ApartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the apt number.
        /// </summary>
        internal static string ApartmentNumber {
            get {
                return ResourceManager.GetString("ApartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Number *.
        /// </summary>
        internal static string ApartmentNumberTitle {
            get {
                return ResourceManager.GetString("ApartmentNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balcony.
        /// </summary>
        internal static string BalconyTitle {
            get {
                return ResourceManager.GetString("BalconyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the number of bathrooms.
        /// </summary>
        internal static string BathroomCount {
            get {
                return ResourceManager.GetString("BathroomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Bathrooms.
        /// </summary>
        internal static string BathroomCountTitle {
            get {
                return ResourceManager.GetString("BathroomCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Size.
        /// </summary>
        internal static string BedSize {
            get {
                return ResourceManager.GetString("BedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the building code.
        /// </summary>
        internal static string BuildingCode {
            get {
                return ResourceManager.GetString("BuildingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Code *.
        /// </summary>
        internal static string BuildingCodeTitle {
            get {
                return ResourceManager.GetString("BuildingCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELED.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose category first..
        /// </summary>
        internal static string CategoryNotSelected {
            get {
                return ResourceManager.GetString("CategoryNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        internal static string CategoryPickerTitle {
            get {
                return ResourceManager.GetString("CategoryPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select category..
        /// </summary>
        internal static string CategorySelectedError {
            get {
                return ResourceManager.GetString("CategorySelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string changelang_English {
            get {
                return ResourceManager.GetString("changelang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string changelang_French {
            get {
                return ResourceManager.GetString("changelang_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string changelang_headerTitle {
            get {
                return ResourceManager.GetString("changelang_headerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        internal static string changelang_Hebrew {
            get {
                return ResourceManager.GetString("changelang_Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string changelang_PickerPlaceholder {
            get {
                return ResourceManager.GetString("changelang_PickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string changelang_Russian {
            get {
                return ResourceManager.GetString("changelang_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Password.
        /// </summary>
        internal static string ChangeyourPassword {
            get {
                return ResourceManager.GetString("ChangeyourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Here....
        /// </summary>
        internal static string ChatDetailMessagePlaceholder {
            get {
                return ResourceManager.GetString("ChatDetailMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        /// </summary>
        internal static string ChatDetailUserMsg1 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing..
        /// </summary>
        internal static string ChatDetailUserMsg2 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        /// </summary>
        internal static string ChatDetailUserMsg3 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        /// </summary>
        internal static string ChatDetailUserMsg4 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9:02 PM.
        /// </summary>
        internal static string ChatDetailUserMsgTime1 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsgTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9:05 PM.
        /// </summary>
        internal static string ChatDetailUserMsgTime2 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsgTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9:10 PM.
        /// </summary>
        internal static string ChatDetailUserMsgTime3 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsgTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9:22 PM.
        /// </summary>
        internal static string ChatDetailUserMsgTime4 {
            get {
                return ResourceManager.GetString("ChatDetailUserMsgTime4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        internal static string ChatListTitle {
            get {
                return ResourceManager.GetString("ChatListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rylle Kincaid.
        /// </summary>
        internal static string ChatListUserName1 {
            get {
                return ResourceManager.GetString("ChatListUserName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirsten Mckellar.
        /// </summary>
        internal static string ChatListUserName2 {
            get {
                return ResourceManager.GetString("ChatListUserName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaun Gardner.
        /// </summary>
        internal static string ChatListUserName3 {
            get {
                return ResourceManager.GetString("ChatListUserName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My selfie game is lacking can....
        /// </summary>
        internal static string ChatUserMsg1 {
            get {
                return ResourceManager.GetString("ChatUserMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the nearest place to....
        /// </summary>
        internal static string ChatUserMsg2 {
            get {
                return ResourceManager.GetString("ChatUserMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok that sounds perfect.
        /// </summary>
        internal static string ChatUserMsg3 {
            get {
                return ResourceManager.GetString("ChatUserMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 min.
        /// </summary>
        internal static string ChatUserMsgTime1 {
            get {
                return ResourceManager.GetString("ChatUserMsgTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 min.
        /// </summary>
        internal static string ChatUserMsgTime2 {
            get {
                return ResourceManager.GetString("ChatUserMsgTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min.
        /// </summary>
        internal static string ChatUserMsgTime3 {
            get {
                return ResourceManager.GetString("ChatUserMsgTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Complete all the tasks..
        /// </summary>
        internal static string CheckListError {
            get {
                return ResourceManager.GetString("CheckListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList.
        /// </summary>
        internal static string CheckListTitle {
            get {
                return ResourceManager.GetString("CheckListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltimore.
        /// </summary>
        internal static string CityValue {
            get {
                return ResourceManager.GetString("CityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE.
        /// </summary>
        internal static string COMPLETE {
            get {
                return ResourceManager.GetString("COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm Password doesn&apos;t match..
        /// </summary>
        internal static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email id..
        /// </summary>
        internal static string ContactUsEmailError {
            get {
                return ResourceManager.GetString("ContactUsEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write message..
        /// </summary>
        internal static string ContactUsMsgError {
            get {
                return ResourceManager.GetString("ContactUsMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name..
        /// </summary>
        internal static string ContactUsNameError {
            get {
                return ResourceManager.GetString("ContactUsNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Country code..
        /// </summary>
        internal static string CountryCodeError {
            get {
                return ResourceManager.GetString("CountryCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER.
        /// </summary>
        internal static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        internal static string CustomerDetailTitle {
            get {
                return ResourceManager.GetString("CustomerDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose date and time..
        /// </summary>
        internal static string DateTimeError {
            get {
                return ResourceManager.GetString("DateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        internal static string DateTimeTitle {
            get {
                return ResourceManager.GetString("DateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14/08/2019 at 10:00 AM.
        /// </summary>
        internal static string DateTimeValue {
            get {
                return ResourceManager.GetString("DateTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write job description here....
        /// </summary>
        internal static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionTitle {
            get {
                return ResourceManager.GetString("DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Number.
        /// </summary>
        internal static string DetailApartmentNumberTitle {
            get {
                return ResourceManager.GetString("DetailApartmentNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Code.
        /// </summary>
        internal static string DetailBuildingCodeTitle {
            get {
                return ResourceManager.GetString("DetailBuildingCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string DetailFloorTitle {
            get {
                return ResourceManager.GetString("DetailFloorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info Updated Successfully..
        /// </summary>
        internal static string DeviceInfoupdated {
            get {
                return ResourceManager.GetString("DeviceInfoupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishwasher.
        /// </summary>
        internal static string DishwasherTitle {
            get {
                return ResourceManager.GetString("DishwasherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DoneBtn {
            get {
                return ResourceManager.GetString("DoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doorman.
        /// </summary>
        internal static string DoormanTitle {
            get {
                return ResourceManager.GetString("DoormanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the number of double beds.
        /// </summary>
        internal static string DoubleBeds {
            get {
                return ResourceManager.GetString("DoubleBeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Double Beds.
        /// </summary>
        internal static string DoubleBedsTitle {
            get {
                return ResourceManager.GetString("DoubleBedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the number of double sopha beds.
        /// </summary>
        internal static string DoubleSophaBeds {
            get {
                return ResourceManager.GetString("DoubleSophaBeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Double Sopha Beds.
        /// </summary>
        internal static string DoubleSophaBedsTitle {
            get {
                return ResourceManager.GetString("DoubleSophaBedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write number of duvet.
        /// </summary>
        internal static string Duvets {
            get {
                return ResourceManager.GetString("Duvets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mention the size of duvet.
        /// </summary>
        internal static string DuvetSize {
            get {
                return ResourceManager.GetString("DuvetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duvet Size.
        /// </summary>
        internal static string DuvetSizeTitle {
            get {
                return ResourceManager.GetString("DuvetSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string DuvetSizeValue {
            get {
                return ResourceManager.GetString("DuvetSizeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Duvets.
        /// </summary>
        internal static string DuvetsTitle {
            get {
                return ResourceManager.GetString("DuvetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT PROFILE.
        /// </summary>
        internal static string EditProfileHeaderTitle {
            get {
                return ResourceManager.GetString("EditProfileHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevator.
        /// </summary>
        internal static string ElevatorTitle {
            get {
                return ResourceManager.GetString("ElevatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email..
        /// </summary>
        internal static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the required records..
        /// </summary>
        internal static string EmptyFieldError {
            get {
                return ResourceManager.GetString("EmptyFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date &amp; Time.
        /// </summary>
        internal static string EndDateTimeTitle {
            get {
                return ResourceManager.GetString("EndDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END TIMER.
        /// </summary>
        internal static string ENDTIMER {
            get {
                return ResourceManager.GetString("ENDTIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occuring while updating the device info..
        /// </summary>
        internal static string ExceptionDeviceInfo {
            get {
                return ResourceManager.GetString("ExceptionDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the floor number.
        /// </summary>
        internal static string FloorNumber {
            get {
                return ResourceManager.GetString("FloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor *.
        /// </summary>
        internal static string FloorTitle {
            get {
                return ResourceManager.GetString("FloorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        internal static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email and we will send you a link to reset your password..
        /// </summary>
        internal static string ForgotYourPasswordText {
            get {
                return ResourceManager.GetString("ForgotYourPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL ADDRESS.
        /// </summary>
        internal static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden.
        /// </summary>
        internal static string GardenTitle {
            get {
                return ResourceManager.GetString("GardenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN PROGRESS.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Rating.
        /// </summary>
        internal static string jobdetail_Jobrating {
            get {
                return ResourceManager.GetString("jobdetail_Jobrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string JobDetailChatOption {
            get {
                return ResourceManager.GetString("JobDetailChatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC Property.
        /// </summary>
        internal static string JobDetailProperty {
            get {
                return ResourceManager.GetString("JobDetailProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing.
        /// </summary>
        internal static string JobDetailServiceCategory {
            get {
                return ResourceManager.GetString("JobDetailServiceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOB DETAILS.
        /// </summary>
        internal static string JobDetailsHeaderTitle {
            get {
                return ResourceManager.GetString("JobDetailsHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Price.
        /// </summary>
        internal static string JobPriceTitle {
            get {
                return ResourceManager.GetString("JobPriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOB REQUEST.
        /// </summary>
        internal static string JobRequest {
            get {
                return ResourceManager.GetString("JobRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOB REQUEST.
        /// </summary>
        internal static string JobRequestHeaderTitle {
            get {
                return ResourceManager.GetString("JobRequestHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Review.
        /// </summary>
        internal static string JobReviewTitle {
            get {
                return ResourceManager.GetString("JobReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        internal static string LoadingMsg {
            get {
                return ResourceManager.GetString("LoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to logout?.
        /// </summary>
        internal static string LogoutMsg {
            get {
                return ResourceManager.GetString("LogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY BOOKINGS.
        /// </summary>
        internal static string MyBookingHeaderTitle {
            get {
                return ResourceManager.GetString("MyBookingHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bookings.
        /// </summary>
        internal static string MyBookings {
            get {
                return ResourceManager.GetString("MyBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Property.
        /// </summary>
        internal static string NameofProperty {
            get {
                return ResourceManager.GetString("NameofProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Property *.
        /// </summary>
        internal static string NameofPropertyTitle {
            get {
                return ResourceManager.GetString("NameofPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User?.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextBtn {
            get {
                return ResourceManager.GetString("NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently you don&apos;t have any chat..
        /// </summary>
        internal static string NoChatListFound {
            get {
                return ResourceManager.GetString("NoChatListFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        internal static string NoInternetError {
            get {
                return ResourceManager.GetString("NoInternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, you don&apos;t have any Booking..
        /// </summary>
        internal static string NoJobRequest {
            get {
                return ResourceManager.GetString("NoJobRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, You don&apos;t have any notification..
        /// </summary>
        internal static string NoNotificationError {
            get {
                return ResourceManager.GetString("NoNotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, You don&apos;t have any property..
        /// </summary>
        internal static string NoPropertyFound {
            get {
                return ResourceManager.GetString("NoPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTIFICATIONS.
        /// </summary>
        internal static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has accepted your request..
        /// </summary>
        internal static string NotificationUserMessage {
            get {
                return ResourceManager.GetString("NotificationUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has sent you quote for appartment service..
        /// </summary>
        internal static string NotificationUserMessageBtn {
            get {
                return ResourceManager.GetString("NotificationUserMessageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nate Parker.
        /// </summary>
        internal static string NotificationUserName {
            get {
                return ResourceManager.GetString("NotificationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 days ago.
        /// </summary>
        internal static string NotificationUserTime {
            get {
                return ResourceManager.GetString("NotificationUserTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        internal static string ParkingTitle {
            get {
                return ResourceManager.GetString("ParkingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDING.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL DETAILS.
        /// </summary>
        internal static string PersonalDetailHeader {
            get {
                return ResourceManager.GetString("PersonalDetailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write number of pillow.
        /// </summary>
        internal static string Pillow {
            get {
                return ResourceManager.GetString("Pillow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Pillows.
        /// </summary>
        internal static string PillowsTitle {
            get {
                return ResourceManager.GetString("PillowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string PoolTitle {
            get {
                return ResourceManager.GetString("PoolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of Services.
        /// </summary>
        internal static string PriceofServices {
            get {
                return ResourceManager.GetString("PriceofServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        internal static string ProfileHeaderTitle {
            get {
                return ResourceManager.GetString("ProfileHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the First and Last name..
        /// </summary>
        internal static string ProfileNameError {
            get {
                return ResourceManager.GetString("ProfileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ProfileUserChangePasswordBtn {
            get {
                return ResourceManager.GetString("ProfileUserChangePasswordBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argele.intili@gmail.com.
        /// </summary>
        internal static string ProfileUserEmail {
            get {
                return ResourceManager.GetString("ProfileUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argele.
        /// </summary>
        internal static string ProfileUserFirstName {
            get {
                return ResourceManager.GetString("ProfileUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intili.
        /// </summary>
        internal static string ProfileUserLastName {
            get {
                return ResourceManager.GetString("ProfileUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argele Intili.
        /// </summary>
        internal static string ProfileUserName {
            get {
                return ResourceManager.GetString("ProfileUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9876541230.
        /// </summary>
        internal static string ProfileUserPhoneNumber {
            get {
                return ResourceManager.GetString("ProfileUserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140307.
        /// </summary>
        internal static string ProfileUserZipCode {
            get {
                return ResourceManager.GetString("ProfileUserZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 142 Palm Avenue, Los angeles, California-90001, USA.
        /// </summary>
        internal static string PropertyAddress {
            get {
                return ResourceManager.GetString("PropertyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address *.
        /// </summary>
        internal static string PropertyAddressTitle {
            get {
                return ResourceManager.GetString("PropertyAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY DETAILS.
        /// </summary>
        internal static string PropertyDetailsHeaderTitle {
            get {
                return ResourceManager.GetString("PropertyDetailsHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string propertyDuvetType_Large {
            get {
                return ResourceManager.GetString("propertyDuvetType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string propertyDuvetType_Medium {
            get {
                return ResourceManager.GetString("propertyDuvetType_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string propertyDuvetType_Small {
            get {
                return ResourceManager.GetString("propertyDuvetType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTIES LIST.
        /// </summary>
        internal static string PropertyListTitle {
            get {
                return ResourceManager.GetString("PropertyListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Property.
        /// </summary>
        internal static string PropertyPickerTitle {
            get {
                return ResourceManager.GetString("PropertyPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PropertyTitle {
            get {
                return ResourceManager.GetString("PropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House\Apartment.
        /// </summary>
        internal static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string propertyType_Apartment {
            get {
                return ResourceManager.GetString("propertyType_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex.
        /// </summary>
        internal static string propertyType_Duplex {
            get {
                return ResourceManager.GetString("propertyType_Duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penthouse.
        /// </summary>
        internal static string propertyType_Penthouse {
            get {
                return ResourceManager.GetString("propertyType_Penthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa.
        /// </summary>
        internal static string propertyType_Villa {
            get {
                return ResourceManager.GetString("propertyType_Villa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Property:.
        /// </summary>
        internal static string PropertyTypeTitle {
            get {
                return ResourceManager.GetString("PropertyTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the number of queen beds.
        /// </summary>
        internal static string Queenbeds {
            get {
                return ResourceManager.GetString("Queenbeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Queen Beds.
        /// </summary>
        internal static string QueenbedsTitle {
            get {
                return ResourceManager.GetString("QueenbedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen Size.
        /// </summary>
        internal static string QueenSize {
            get {
                return ResourceManager.GetString("QueenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Images.
        /// </summary>
        internal static string ReferenceImagesTitle {
            get {
                return ResourceManager.GetString("ReferenceImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account for using Broom Service..
        /// </summary>
        internal static string RegisterHeaderMsg {
            get {
                return ResourceManager.GetString("RegisterHeaderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill name, email, password, phone number, country and country code..
        /// </summary>
        internal static string RegisterServerError {
            get {
                return ResourceManager.GetString("RegisterServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJECT.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the required fields..
        /// </summary>
        internal static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Property.
        /// </summary>
        internal static string SearchProperty {
            get {
                return ResourceManager.GetString("SearchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendBtn {
            get {
                return ResourceManager.GetString("SendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND QUOTE.
        /// </summary>
        internal static string SendQuote {
            get {
                return ResourceManager.GetString("SendQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from Server Side..
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE CATEGORIES.
        /// </summary>
        internal static string ServiceCategoryHeaderTitle {
            get {
                return ResourceManager.GetString("ServiceCategoryHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed, July 30, 2018.
        /// </summary>
        internal static string ServiceDate {
            get {
                return ResourceManager.GetString("ServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Description.
        /// </summary>
        internal static string ServiceDescriptionTitle {
            get {
                return ResourceManager.GetString("ServiceDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE PROVIDER.
        /// </summary>
        internal static string SERVICEPROVIDER {
            get {
                return ResourceManager.GetString("SERVICEPROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nate Parker.
        /// </summary>
        internal static string ServiceProviderName {
            get {
                return ResourceManager.GetString("ServiceProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider Name.
        /// </summary>
        internal static string ServiceProviderNameTitle {
            get {
                return ResourceManager.GetString("ServiceProviderNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE SUBCATEGORIES.
        /// </summary>
        internal static string ServiceSubCategoryHeaderTitle {
            get {
                return ResourceManager.GetString("ServiceSubCategoryHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE SUBSUBCATEGORIES.
        /// </summary>
        internal static string ServiceSubSubCategoryHeaderTitle {
            get {
                return ResourceManager.GetString("ServiceSubSubCategoryHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string ServiceTime {
            get {
                return ResourceManager.GetString("ServiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing Service.
        /// </summary>
        internal static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term AirBnb Apartment.
        /// </summary>
        internal static string ShortTermAirBnbAprtment {
            get {
                return ResourceManager.GetString("ShortTermAirBnbAprtment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the number of single beds.
        /// </summary>
        internal static string Singlebeds {
            get {
                return ResourceManager.GetString("Singlebeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Single Beds.
        /// </summary>
        internal static string SinglebedsTitle {
            get {
                return ResourceManager.GetString("SinglebedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the number of single sopha beds.
        /// </summary>
        internal static string SingleSophabeds {
            get {
                return ResourceManager.GetString("SingleSophabeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Single Sopha Beds.
        /// </summary>
        internal static string SingleSophabedsTitle {
            get {
                return ResourceManager.GetString("SingleSophabedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date &amp; Time.
        /// </summary>
        internal static string StartDateTimeTitle {
            get {
                return ResourceManager.GetString("StartDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START JOB.
        /// </summary>
        internal static string STARTJOB {
            get {
                return ResourceManager.GetString("STARTJOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START TIMER.
        /// </summary>
        internal static string STARTTIMER {
            get {
                return ResourceManager.GetString("STARTTIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one sub-category.
        /// </summary>
        internal static string SubCategoryError {
            get {
                return ResourceManager.GetString("SubCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Service.
        /// </summary>
        internal static string SubCategoryTitle {
            get {
                return ResourceManager.GetString("SubCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermandConditions {
            get {
                return ResourceManager.GetString("TermandConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms &amp; conditions..
        /// </summary>
        internal static string TermConditionError {
            get {
                return ResourceManager.GetString("TermConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read &amp; agree with the .
        /// </summary>
        internal static string TermNcondtionMsg {
            get {
                return ResourceManager.GetString("TermNcondtionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Property.
        /// </summary>
        internal static string TypeofProperty {
            get {
                return ResourceManager.GetString("TypeofProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Property *.
        /// </summary>
        internal static string TypeofPropertyTitle {
            get {
                return ResourceManager.GetString("TypeofPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Service.
        /// </summary>
        internal static string TypeOfServiceTitle {
            get {
                return ResourceManager.GetString("TypeOfServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPCOMING.
        /// </summary>
        internal static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateBtn {
            get {
                return ResourceManager.GetString("UpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Property.
        /// </summary>
        internal static string UpdatePropertyPageTitle {
            get {
                return ResourceManager.GetString("UpdatePropertyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details &gt;.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        internal static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Broom Service!.
        /// </summary>
        internal static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Broom Service!.
        /// </summary>
        internal static string WelcomeToBroomService {
            get {
                return ResourceManager.GetString("WelcomeToBroomService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKER.
        /// </summary>
        internal static string WORKER {
            get {
                return ResourceManager.GetString("WORKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rylle Kincaid.
        /// </summary>
        internal static string WorkerName {
            get {
                return ResourceManager.GetString("WorkerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumber.
        /// </summary>
        internal static string WorkerServiceName {
            get {
                return ResourceManager.GetString("WorkerServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write here....
        /// </summary>
        internal static string Writehere {
            get {
                return ResourceManager.GetString("Writehere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        internal static string Zipcode {
            get {
                return ResourceManager.GetString("Zipcode", resourceCulture);
            }
        }
    }
}
